namespace StartreckSimulator.Models
{
    public enum ClassificationTypes
    {
        Person,
        Vehicle,
        Animal,
        Sheep,
        Pig, 
        Donkey,
        Horse, 
        Rabbit, 
        False, 
        ArmedPerson, 
        Group, 
        Balloon, 
        Boat, 
        ArmoredVehicle, 
        Kite, 
        Aircraft, 
        Drone,
        PickupTruck, 
        Tractor, 
        Track, 
        Motorcycle,
        Wagon, 
        Bird
    }
}